language: go
go:
    - 1.12.x
    - 1.13.x

go_import_path: github.com/containerd/fifo

env:
  - GO111MODULE=on

install:
  - pushd ..; go get -u github.com/vbatts/git-validation; popd
  - pushd ..; go get -u github.com/kunalkushwaha/ltag; popd

before_script:
  - pushd ..; git clone https://github.com/containerd/project; popd

script:
  - DCO_VERBOSITY=-q ../project/script/validate/dco
  - ../project/script/validate/fileheader ../project/
  - make test
